version: '3.9'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

  api:
    container_name: api
    build: 
      context: ./server
    ports:
      - '3001:3001'
    depends_on:
      - db

volumes:
  data: